---
- name: "Hosting PHP application in Redhat and Debian"
  hosts: all
  become: true
  tasks:
    - include_tasks: amazon.yml
      when: ansible_os_family == "RedHat"
    - include_tasks: ubuntu.yml
      when: ansible_os_family == "Debian"
